.\"
.\" License: GNU GPLv2+
.\"
.TH DOKUWIKI-SYNC.SH 1 "2017-09-30" "" "amw scripts"
.SH NAME
dokuwiki-sync.sh \- backup/restore/synchronise dokuwiki trees
.SH SYNOPSIS
.B dokuwiki-sync.sh
[\-n] [\-x] [\-v] [\-h] <command> 
.RI [ file... ]
.SH DESCRIPTION
.B  dokuwiki-sync.sh
is a script to ease synchronising two dokuwiki trees possibly on different machines by exporting
that data and updating changes between two trees
.PP
Run 
.B dokuwiki-sync.sh -h
.BR
to see the full set of options
